#include <iostream>
#include <string>
#include <chrono>
// Auto-generated by CMake from telemetry.proto
#include "telemetry.pb.h" 
using namespace com::lagrange::telemetry;

// Utility function to get current timestamp in milliseconds
int64_t getCurrentTimestampMs() {
    auto now = std::chrono::system_clock::now();
    return std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()).count();
}

int main() {
    // Verify that the version of the library that we linked against is
    // compatible with the version of the headers we compiled against.
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    std::cout << "[LagRange] Initializing telemetry agent..." << std::endl;

    // 1. INITIALIZE ROOT ENVELOPE
    AgentMessage payload;
    payload.set_agent_id("lagrange-node-prod-01");
    payload.set_api_key("sk_live_vanguard_88f92a");
    payload.set_timestamp_ms(getCurrentTimestampMs());

    // 2. POPULATE SYSTEM METRICS
    // We allocate this on the heap. Protobuf will take ownership and delete it automatically.
    SystemMetrics* sysMetrics = new SystemMetrics();

    // CPU & RAM Usage
    sysMetrics->set_cpu_usage_percent(12.4);         // TODO: Hook to PDH/proc
    sysMetrics->set_ram_total_mb(16384.0);
    sysMetrics->set_ram_used_mb(8192.5);
    
    // Disk Usage & IO
    sysMetrics->set_disk_total_mb(512000.0);
    sysMetrics->set_disk_used_mb(256000.0);
    sysMetrics->set_disk_read_kbps(150.5);
    sysMetrics->set_disk_write_kbps(45.2);
    
    // Process, Uptime, & Users
    sysMetrics->set_active_processes(215);
    sysMetrics->set_system_uptime_seconds(86400);    // 1 day uptime
    sysMetrics->set_logged_in_users(2);
    
    // Temperature (Optional field handled cleanly)
    sysMetrics->set_cpu_temperature_celsius(45.5);

    // Attach SystemMetrics to the main payload
    payload.set_allocated_system_metrics(sysMetrics);

    // 3. POPULATE NETWORK STATS (As a separate payload concept)
    AgentMessage netPayload;
    netPayload.set_agent_id("lagrange-node-prod-01");
    netPayload.set_timestamp_ms(getCurrentTimestampMs());

    NetworkStats* netStats = new NetworkStats();
    
    // Network Speed & Ports
    netStats->set_network_tx_kbps(1024.0); // 1 MB/s upload
    netStats->set_network_rx_kbps(5120.0); // 5 MB/s download
    netStats->set_open_ports_count(22);

    netPayload.set_allocated_network_stats(netStats);

    // 4. SERIALIZE TO BINARY (The Network Push)
    std::string binarySystemData;
    if (payload.SerializeToString(&binarySystemData)) {
        std::cout << "[LagRange] Successfully serialized System Metrics." << std::endl;
        std::cout << " -> Payload Size: " << binarySystemData.length() << " bytes." << std::endl;
        // Here is where Boost.Asio WebSockets will push binarySystemData to Spring Boot
    } else {
        std::cerr << "[LagRange] Failed to serialize system metrics!" << std::endl;
    }

    // Clean up Protobuf memory allocations
    google::protobuf::ShutdownProtobufLibrary();

    return 0;
}